### ISSUE TITLE
Merge with admin repo

### ISSUE THREAD

**Issue by junghans** [votca/dev-tools#8]
Maybe we should merge this repo with the admin repo: https://github.com/votca/admin/tree/master/scripts, the only useful script in there is https://github.com/votca/admin/blob/master/scripts/make_release.sh

the other script could be deleted.

Multi-repo merge:
```
git fetch https://github.com/votca/admin.git master
git merge --allow-unrelated-histories FETCH_HEAD
```

**Comment by JoshuaSBrown** [comment]
Sounds like a good idea, only now seeing this. Though I think the name dev-tools is a little more clear about the contents than admin.

**Comment by junghans** [comment]
See #9
